### ISSUE TITLE
is it possible to got assembly code for the RVM code?

### ISSUE THREAD

**Issue by jiamo** [udem-dlteam/ribbit#11]
The print hello rvm code is `);'u?>vD?>vRD?>vRA?>vRA?>vR:?>vR=!(:lkm!':lkv6y`
and after decode , it's byte code array is 
`[3, 19, [3, 0, [3, 1, [0, [[0, [[...], [[[0, 0, 5], [[0, 0, 5], 0, 3], 2], [[[0, 0, 5], [[0, 0, 5], 0, 3], 2], [[[0, 0, 5], [[0, 0, 5], 0, 3], 2], [[0, [[0, 0, 5], 0, 3], 2], [[0, [[0, 0, 5], 0, 3], 2], [[0, [[0, 0, 5], 0, 3], 2], [0, 0, 5], 0], 0], 0], 0], 0], 0], 0], 1], [[0, 0, 5], 0, 3], 2], [1, [0, [[0, 0, 5], 0, 3], 2], [3, 2, [3, 0, [3, 1, [0, [[0, [[...], [[[0, 0, 5], [[0, 0, 5], 0, 3], 2], [[[0, 0, 5], [[0, 0, 5], 0, 3], 2], [[[0, 0, 5], [[0, 0, 5], 0, 3], 2], [[0, [[0, 0, 5], 0, 3], 2], [[0, [[0, 0, 5], 0, 3], 2], [[0, [[0, 0, 5], 0, 3], 2], [0, 0, 5], 0], 0], 0], 0], 0], 0], 0], 1], [[0, 0, 5], 0, 3], 2], [1, [0, [[0, 0, 5], 0, 3], 2], [3, 72, [0, [0, [[0, 0, 5], 0, 3], 2], [0, [0, [[0, 0, 5], 0, 3], 2], [3, 69, [0, [0, [[0, 0, 5], 0, 3], 2], [0, [0, [[0, 0, 5], 0, 3], 2], [3, 76, [0, [0, [[0, 0, 5], 0, 3], 2], [0, [0, [[0, 0, 5], 0, 3], 2], [3, 76, [0, [0, [[0, 0, 5], 0, 3], 2], [0, [0, [[0, 0, 5], 0, 3], 2], [3, 79, [0, [0, [[0, 0, 5], 0, 3], 2], [0, [0, [[0, 0, 5], 0, 3], 2], [3, 33, [0, [0, [[0, 0, 5], 0, 3], 2], [0, [0, [[0, 0, 5], 0, 3], 2], [3, 10, [0, [0, [[0, 0, 5], 0, 3], 2], 0]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]`

I am wondering can we got assembly code for rvm code such like 

```
const 19 
const 0
const 1
rib
...
call
pop
...

```

**Comment by feeley** [comment]
You can get the "human-readable" RVM code with the `-vvv` (verbosity level 3) command line option:

```
$ echo "(+ 11 22)" > add.scm
$ gsi rsc.scm -t rvm -l empty -vvv add.scm
*** RVM code:
#(#(0 0 #(const 11 #(const 22 #(jump/call + 0)))) () 1)
*** exports:
((+ . +) (arg1 . arg1) (arg2 . arg2) (close . close) (id . id))
*** RVM code length: 20 bytes
#+,,,,;'v9v.!':lkv1y
```

Note that the RVM code is really a tree made up of ribs, so it does not have the linear structure that would allow writing it out like you suggest.

**Comment by jiamo** [comment]
Thanks.
