### ISSUE TITLE
Missing makefiles?

### ISSUE THREAD

**Issue by shawnw** [udem-dlteam/ribbit#23]
A few host sub directories have makefiles that reference `../../makefile-common.mk`, which doesn't exist in the repository. And the main readme mentions some make targets that can be run from the `src` directory, but there's no Makefile there either.

**Comment by feeley** [comment]
Fixed by e837b8be0198d831204625bfc4bf09d068d92a1b .  Somehow I forgot to commit these files when the host makefiles were updated.
