### ISSUE TITLE
Irritating/ugly error message with the basic rsc.exe invocation

### ISSUE THREAD

**Issue by bentxt** [udem-dlteam/ribbit#79]
```
 cat hello.scm
(display "foo")

./rsc.exe hello.scm
*** ERROR IN extract-feature-names -- (Argument 3, clist1) LIST expected
(fold '#<procedure #2> '() #f)
```

**Comment by leo-ard** [comment]
Thanks for reporting this. I think there is some errors with the `rvm` target (the target that is only spitting out the encoded ribs). I'll have a look

**Comment by leo-ard** [comment]
I did a quickfix with the #81 PR. To make sure this doesn't happen again, we should add the RVM host to the CI (see #82). Thanks for reporting this!
